# Write your code here :-)
print("========================")
print("      HELLO WORLD       ")
print("    by Mr. Baldus       ")
print("========================")
print("")
print("Hello, World!")
name = input("What is your name? ")
print(f"Hello, {name}")